GPTK: MinMaxDesign Class Reference
MinMaxDesign Class Reference
#include <MinMaxDesign.h>
Public Member Functions
MinMaxDesign (int nsamples=100)
~MinMaxDesign ()
ivec subsample (mat X, int sample_size)
Private Member Functions
double distanceMax (mat X)
Private Attributes
int nsamples
Detailed Description
MIN MAX DISTANCE RANDOM DESIGN
This returns a random subsample from a set of locations in which the maximum distance between any two points is minimised. The minimisation is achieved by taking the "best" subsample (with respect to the max distance between points) out of NSAMPLE similar random subsamples.
Definition at line 15 of file MinMaxDesign.h.
Constructor & Destructor Documentation
MinMaxDesign::MinMaxDesign (int nsamples = 100)
Definition at line 3 of file MinMaxDesign.cpp.
References nsamples.
MinMaxDesign::~MinMaxDesign ()
Definition at line 14 of file MinMaxDesign.cpp.
Member Function Documentation
ivec MinMaxDesign::subsample (mat X, int n) [virtual]
Returns a random subsample of X of size n which has minimum (amongst a set of NSAMPLES similar subsamples) maximum distance between points.
Implements Design.
Definition at line 23 of file MinMaxDesign.cpp.
References distanceMax(), nsamples, and itppext::randperm().
double MinMaxDesign::distanceMax (mat X) [private]
Returns the maximum distance between any 2 points from X
Definition at line 54 of file MinMaxDesign.cpp.
Referenced by subsample().
Member Data Documentation
int MinMaxDesign::nsamples [private]
Definition at line 25 of file MinMaxDesign.h.
Referenced by MinMaxDesign(), and subsample().
The documentation for this class was generated from the following files:
src/design/MinMaxDesign.h
src/design/MinMaxDesign.cpp