GPTK: SumCF Class Reference
SumCF Class Reference
#include <SumCF.h>
Public Member Functions
SumCF ()
SumCF (CovarianceFunction &cf)
~SumCF ()
double computeElement (const vec &A, const vec &B) const
double computeDiagonalElement (const vec &A) const
void covarianceGradient (mat &G, const int p, const mat &X) const
void setParameter (const int parameterNumber, const double value)
double getParameter (const int parameterNumber) const
string getParameterName (const int parameterNumber) const
void setTransformedParameters (const vec p)
vec getTransformedParameters ()
void setTransform (int parameterNumber, Transform *newTransform)
Transform * getTransform (int parameterNumber) const
void add (CovarianceFunction &cf)
void displayCovarianceParameters (int nspaces=0) const
Private Member Functions
void reindex (int &cfIndex, int &parcfIndex, int parIndex) const
Private Attributes
vector< CovarianceFunction * > covFunctions
Detailed Description
Sum of covariance functions. This allows to build complex covariance functions using a mixture of basic ones.
Definition at line 47 of file SumCF.h.
Constructor & Destructor Documentation
SumCF::SumCF ()
Constructor
Definition at line 6 of file SumCF.cpp.
References covFunctions.
SumCF::SumCF (CovarianceFunction & cf)
Definition at line 12 of file SumCF.cpp.
References covFunctions.
SumCF::~SumCF ()
Destructor
Definition at line 24 of file SumCF.cpp.
Member Function Documentation
double SumCF::computeElement (const vec & A, const vec & B) const [inline, virtual]
Computes the covariance between inputs A and B
Parameters:
A the first input
B the second input
Returns:
the covariance between A and B
Implements CovarianceFunction.
Definition at line 48 of file SumCF.cpp.
References covFunctions.
double SumCF::computeDiagonalElement (const vec & A) const [inline, virtual]
Computes the variance of an input A
Parameters:
A an input
Returns:
the variance of A
Reimplemented from CovarianceFunction.
Definition at line 67 of file SumCF.cpp.
References covFunctions.
void SumCF::covarianceGradient (mat & D, const int p, const mat & X) const [virtual]
Gradient of the covariance matrix with respect to a given parameter, i.e. d/dparameter cov(X,X)
Parameters:
D the gradient of the covariance matrix cov(X,X) with respect to parameter number p
p the parameter number
X a set of inputs
Implements CovarianceFunction.
Definition at line 109 of file SumCF.cpp.
References covFunctions, and reindex().
void SumCF::setParameter (const int p, const double value) [virtual]
Set the value for a given parameter. See setParameters for a description of parameter indexing in SumCF.
Parameters:
p the parameter number, between 0 and the total number of parameters (from all covariance functions)
value the new value for the parameter
Reimplemented from CovarianceFunction.
Definition at line 204 of file SumCF.cpp.
References covFunctions, and reindex().
double SumCF::getParameter (const int p) const [virtual]
Get a given parameter (out of the parameters from all covariance functions)
Parameters:
p the parameter number, between 0 and the total number of parameters
Returns:
Note:
parameters are indexed in the order in which the covariance functions are added to the sum, i.e. for a sum of 2 covariance functions, each with 3 parameters, parameters 0-2 correspond to the parameters of the 1st covariance function, and parameters 3-5 correspond to those of the second covariance function.
See also:
reindex
Reimplemented from CovarianceFunction.
Definition at line 225 of file SumCF.cpp.
References covFunctions, and reindex().
string SumCF::getParameterName (const int p) const [virtual]
Return the name of the given parameter. See setParameters for a description of parameter indexing in SumCF.
Parameters:
p the parameter number, between 0 and the total number of parameters (from all covariance functions)
Returns:
the name of the parameter
Reimplemented from CovarianceFunction.
Definition at line 244 of file SumCF.cpp.
References covFunctions, and reindex().
void SumCF::setTransformedParameters (const vec pvec) [virtual]
Set all parameters from a vector of transformed values
Parameters:
pvec a vector of parameter values (in transformed space, e.g. log of the actual value for log-transformed parameters)
Reimplemented from CovarianceFunction.
Definition at line 159 of file SumCF.cpp.
References covFunctions.
vec SumCF::getTransformedParameters () [virtual]
Get a vector of transformed parameter values
Returns:
a vector of transformed parameter values (e.g. log of the parameter value if the parameter has a log-transform)
Reimplemented from CovarianceFunction.
Definition at line 182 of file SumCF.cpp.
References covFunctions.
void SumCF::setTransform (int p, Transform * t) [virtual]
Set the transform for parameter number p
Parameters:
p the parameter number
t a pointer to the new transform for parameter number p
Reimplemented from CovarianceFunction.
Definition at line 142 of file SumCF.cpp.
References covFunctions, and reindex().
Transform * SumCF::getTransform (int p) const [virtual]
Return the transform for parameter number p
Parameters:
p the parameter number
Returns:
a pointer to the transform object for p
Reimplemented from CovarianceFunction.
Definition at line 125 of file SumCF.cpp.
References covFunctions, and reindex().
void SumCF::add (CovarianceFunction & cf)
Add a covariance function to the sum
Parameters:
cf a covariance function object
Definition at line 34 of file SumCF.cpp.
References covFunctions, CovarianceFunction::getNumberParameters(), and CovarianceFunction::numberParameters.
void SumCF::displayCovarianceParameters (int nspaces = 0) const [virtual]
Display information about the current parameters of the covariance functions. This can be indented by an optional number of space characters (useful for mixtures of nested covariance functions).
Parameters:
nspaces Number of space characters to indent by.
Reimplemented from CovarianceFunction.
Definition at line 87 of file SumCF.cpp.
References covFunctions.
void SumCF::reindex (int & cfIndex, int & parcfIndex, int parIndex) const [private]
Definition at line 269 of file SumCF.cpp.
References covFunctions, and CovarianceFunction::getNumberParameters().
Referenced by covarianceGradient(), getParameter(), getParameterName(), getTransform(), setParameter(), and setTransform().
Member Data Documentation
vector<CovarianceFunction *> SumCF::covFunctions [private]
Definition at line 76 of file SumCF.h.
Referenced by add(), computeDiagonalElement(), computeElement(), covarianceGradient(), displayCovarianceParameters(), getParameter(), getParameterName(), getTransform(), getTransformedParameters(), reindex(), setParameter(), setTransform(), setTransformedParameters(), and SumCF().
The documentation for this class was generated from the following files:
src/covariance_functions/SumCF.h
src/covariance_functions/SumCF.cpp