GPTK: ConstantCF Class Reference
ConstantCF Class Reference
#include <ConstantCF.h>
Public Member Functions
ConstantCF (double amp)
virtual ~ConstantCF ()
double computeElement (const vec &A, const vec &B) const
double computeDiagonalElement (const vec &A) const
virtual void covarianceGradient (mat &grad, const int parameterNumber, const mat &X) const
Private Attributes
double & bias
Detailed Description
Definition at line 36 of file ConstantCF.h.
Constructor & Destructor Documentation
ConstantCF::ConstantCF (double _bias)
Initialise constant covariance object The bias field is a reference to the first element in the array of parameters.
Definition at line 8 of file ConstantCF.cpp.
References bias, and CovarianceFunction::parametersNames.
ConstantCF::~ConstantCF () [virtual]
Definition at line 15 of file ConstantCF.cpp.
Member Function Documentation
double ConstantCF::computeElement (const vec & A, const vec & B) const [inline, virtual]
Implements CovarianceFunction.
Definition at line 19 of file ConstantCF.cpp.
References bias.
double ConstantCF::computeDiagonalElement (const vec & A) const [inline, virtual]
Compute the variance of a diagonal element, i.e. cov(A,A) This is the default and returns computeElement(A,A). This should be overridden when possible with a more efficient implementation, specific to the type of covariance (for instance, for stationary covariance functions, this takes the value of the variance parameter).
Reimplemented from CovarianceFunction.
Definition at line 24 of file ConstantCF.cpp.
References bias.
void ConstantCF::covarianceGradient (mat & grad, const int parameterNumber, const mat & X) const [virtual]
Implements CovarianceFunction.
Definition at line 29 of file ConstantCF.cpp.
References CovarianceFunction::getParameter(), CovarianceFunction::getTransform(), and Transform::gradientTransform().
Member Data Documentation
double& ConstantCF::bias [private]
Definition at line 48 of file ConstantCF.h.
Referenced by computeDiagonalElement(), computeElement(), and ConstantCF().
The documentation for this class was generated from the following files:
src/covariance_functions/ConstantCF.h
src/covariance_functions/ConstantCF.cpp