GPTK: Optimisable Class Reference
Optimisable Class Reference
#include <Optimisable.h>
Public Member Functions
virtual double objective () const =0
virtual vec gradient () const =0
virtual vec getTransformedParameters () const =0
virtual void setTransformedParameters (const vec p)=0
Detailed Description
Definition at line 42 of file Optimisable.h.
Member Function Documentation
virtual double Optimisable::objective () const [pure virtual]
Implemented in GaussianProcess, and PSGP.
Referenced by ModelTrainer::errorFunction().
virtual vec Optimisable::gradient () const [pure virtual]
Implemented in GaussianProcess, and PSGP.
Referenced by ModelTrainer::checkGradient(), and ModelTrainer::errorGradients().
virtual vec Optimisable::getTransformedParameters () const [pure virtual]
Implemented in GaussianProcess, and PSGP.
Referenced by ModelTrainer::getParameters(), and ModelTrainer::setParameters().
virtual void Optimisable::setTransformedParameters (const vec p) [pure virtual]
Implemented in GaussianProcess, and PSGP.
Referenced by ModelTrainer::setParameters().
The documentation for this class was generated from the following file:
src/optimisation/Optimisable.h