GPTK: GaussianProcess Class Reference
GaussianProcess Class Reference
#include <GaussianProcess.h>
Public Member Functions
GaussianProcess (int Inputs, int Outputs, mat &Xdata, vec &ydata, CovarianceFunction &cf)
virtual ~GaussianProcess ()
void makePredictions (vec &Mean, vec &Variance, const mat &Xpred, const mat &C) const
void makePredictions (vec &Mean, vec &Variance, const mat &Xpred, CovarianceFunction &cf) const
void makePredictions (vec &Mean, vec &Variance, const mat &Xpred) const
double loglikelihood () const
vec getTransformedParameters () const
void setTransformedParameters (const vec p)
double objective () const
vec gradient () const
void estimateParameters ()
Private Member Functions
mat computeCholesky (const mat &iM) const
mat computeInverseFromCholesky (const mat &C) const
vec getGradientVector () const
Private Attributes
CovarianceFunction & covFunc
mat & Locations
vec & Observations
Detailed Description
Definition at line 42 of file GaussianProcess.h.
Constructor & Destructor Documentation
GaussianProcess::GaussianProcess (int Inputs, int Outputs, mat & Xdata, vec & ydata, CovarianceFunction & cf)
Definition at line 6 of file GaussianProcess.cpp.
References Locations, and Observations.
GaussianProcess::~GaussianProcess () [virtual]
Definition at line 12 of file GaussianProcess.cpp.
Member Function Documentation
void GaussianProcess::makePredictions (vec & Mean, vec & Variance, const mat & Xpred, const mat & C) const
Definition at line 41 of file GaussianProcess.cpp.
References computeCholesky(), CovarianceFunction::computeDiagonal(), CovarianceFunction::covariance(), covFunc, Locations, and Observations.
Referenced by makePredictions().
void GaussianProcess::makePredictions (vec & Mean, vec & Variance, const mat & Xpred, CovarianceFunction & cf) const
Definition at line 21 of file GaussianProcess.cpp.
References computeCholesky(), CovarianceFunction::computeDiagonal(), CovarianceFunction::covariance(), covFunc, Locations, and Observations.
void GaussianProcess::makePredictions (vec & Mean, vec & Variance, const mat & Xpred) const
Definition at line 16 of file GaussianProcess.cpp.
References covFunc, and makePredictions().
double GaussianProcess::loglikelihood () const
Definition at line 81 of file GaussianProcess.cpp.
References computeCholesky(), computeInverseFromCholesky(), CovarianceFunction::covariance(), covFunc, Locations, and Observations.
Referenced by objective().
vec GaussianProcess::getTransformedParameters () const [virtual]
Return the transformed parameters of the covariance function
Returns:
the transformed parameters of the covariance function
Implements Optimisable.
Definition at line 109 of file GaussianProcess.cpp.
References covFunc, and CovarianceFunction::getTransformedParameters().
void GaussianProcess::setTransformedParameters (const vec pvec) [virtual]
Set the parameters of the covariance function using the transformed (e.g. in log-space) values in pvec.
Parameters:
pvec a vector of transformed parameters values
Implements Optimisable.
Definition at line 121 of file GaussianProcess.cpp.
References covFunc, and CovarianceFunction::setTransformedParameters().
double GaussianProcess::objective () const [virtual]
Returns:
Implements Optimisable.
Definition at line 130 of file GaussianProcess.cpp.
References loglikelihood().
vec GaussianProcess::gradient () const [virtual]
Implements Optimisable.
Definition at line 136 of file GaussianProcess.cpp.
References computeCholesky(), computeInverseFromCholesky(), CovarianceFunction::covariance(), CovarianceFunction::covarianceGradient(), covFunc, CovarianceFunction::getNumberParameters(), Locations, and Observations.
Referenced by getGradientVector().
void GaussianProcess::estimateParameters ()
mat GaussianProcess::computeCholesky (const mat & iM) const [private]
Definition at line 174 of file GaussianProcess.cpp.
Referenced by computeInverseFromCholesky(), gradient(), loglikelihood(), and makePredictions().
mat GaussianProcess::computeInverseFromCholesky (const mat & C) const [private]
Definition at line 211 of file GaussianProcess.cpp.
References computeCholesky().
Referenced by gradient(), and loglikelihood().
vec GaussianProcess::getGradientVector () const [private]
Definition at line 169 of file GaussianProcess.cpp.
References gradient().
Member Data Documentation
CovarianceFunction& GaussianProcess::covFunc [private]
Definition at line 68 of file GaussianProcess.h.
Referenced by getTransformedParameters(), gradient(), loglikelihood(), makePredictions(), and setTransformedParameters().
mat& GaussianProcess::Locations [private]
Definition at line 69 of file GaussianProcess.h.
Referenced by GaussianProcess(), gradient(), loglikelihood(), and makePredictions().
vec& GaussianProcess::Observations [private]
Definition at line 70 of file GaussianProcess.h.
Referenced by GaussianProcess(), gradient(), loglikelihood(), and makePredictions().
The documentation for this class was generated from the following files:
src/gaussian_processes/GaussianProcess.h
src/gaussian_processes/GaussianProcess.cpp