GPTK: StationaryCF Class Reference
StationaryCF Class Reference
#include <StationaryCF.h>
Public Member Functions
StationaryCF (string name, double variance, double lengthScale)
virtual ~StationaryCF ()
virtual void covariance (mat &C, const mat &X) const
virtual void covarianceGradient (mat &grad, const int parameterNumber, const mat &X) const
Static Public Member Functions
static void sqDistMatrix (mat &D, const mat X)
static double sqDist (vec u, vec v)
Protected Member Functions
virtual double computeElement (const vec &u, const vec &v) const
virtual double computeDiagonalElement (const vec &u) const
double computeElement (double sqDist) const
virtual double correlation (double sqDist) const =0
virtual double correlationGradient (int paramNumber, double sqDist) const =0
void applyCorrelation (mat &sqDist) const
void applyCorrelationGradient (int paramNumber, mat &sqDist) const
Protected Attributes
double & variance
double & lengthScale
Detailed Description
StationaryCF.h
Created on: 27 Oct 2009 Author: barillrl Stationary covariance function. This is the base class for stationary covariance functions of the form: sigma * k(sqdit), where sigma is a scaling factor (process variance) and k is a correlation function which only depends on the squared distance between two inputs (sqdist).
Definition at line 20 of file StationaryCF.h.
Constructor & Destructor Documentation
StationaryCF::StationaryCF (string name, double _lengthScale, double _variance)
Default constructor
Parameters:
_variance Process variance
_lengthScale Correlation length scale
name Identifier of the covariance function
Definition at line 17 of file StationaryCF.cpp.
References lengthScale, CovarianceFunction::parametersNames, and variance.
StationaryCF::~StationaryCF () [virtual]
Default destructor
Definition at line 33 of file StationaryCF.cpp.
Member Function Documentation
void StationaryCF::covariance (mat & C, const mat & X) const [virtual]
Computes the symmetric covariance matrix between all inputs in X.
Parameters:
C the covariance matrix cov(X,X)
X a set of (row) inputs
Reimplemented from CovarianceFunction.
Definition at line 80 of file StationaryCF.cpp.
References applyCorrelation(), sqDistMatrix(), and variance.
void StationaryCF::covarianceGradient (mat & D, const int p, const mat & X) const [virtual]
Gradient of the covariance matrix with respect to a given parameter, i.e. d/dp cov(X,X)
Parameters:
D the gradient of the covariance matrix cov(X,X) with respect to parameter number p
p the parameter number
X a set of inputs
Implements CovarianceFunction.
Definition at line 102 of file StationaryCF.cpp.
References applyCorrelation(), applyCorrelationGradient(), CovarianceFunction::getTransform(), Transform::gradientTransform(), CovarianceFunction::numberParameters, CovarianceFunction::parameters, sqDistMatrix(), and variance.
void StationaryCF::sqDistMatrix (mat & D, const mat X) [static]
Computes the matrix of square distances between any two inputs in X.
Parameters:
D the matrix of squared distances
X a set of (row) inputs
Definition at line 188 of file StationaryCF.cpp.
References sqDist().
Referenced by covariance(), and covarianceGradient().
double StationaryCF::sqDist (vec u, vec v) [static]
Compute the square distance between two vectors (i.e. the squared 2-norm)
Parameters:
u the first vector
v the second vector
Returns:
the squared distance between u and v
Definition at line 172 of file StationaryCF.cpp.
Referenced by computeElement(), and sqDistMatrix().
double StationaryCF::computeElement (const vec & u, const vec & v) const [protected, virtual]
Computes the covariance between inputs u and v
Parameters:
u the first input
v the second input
Returns:
the covariance between u and v
Implements CovarianceFunction.
Definition at line 46 of file StationaryCF.cpp.
References sqDist().
double StationaryCF::computeDiagonalElement (const vec & u) const [protected, virtual]
Compute the auto-covariance of input u (for stationary covariance functions, this simply returns the process variance)
Parameters:
u the input
Returns:
the auto-covariance of u (i.e. the process variance)
Reimplemented from CovarianceFunction.
Definition at line 59 of file StationaryCF.cpp.
References correlation(), and variance.
double StationaryCF::computeElement (double sqDist) const [protected]
Compute the covariance for a given squared distance
Definition at line 68 of file StationaryCF.cpp.
References correlation(), and variance.
virtual double StationaryCF::correlation (double sqDist) const [protected, pure virtual]
Implemented in ExponentialCF, GaussianCF, Matern3CF, and Matern5CF.
Referenced by applyCorrelation(), computeDiagonalElement(), and computeElement().
virtual double StationaryCF::correlationGradient (int paramNumber, double sqDist) const [protected, pure virtual]
Implemented in ExponentialCF, GaussianCF, Matern3CF, and Matern5CF.
Referenced by applyCorrelationGradient().
void StationaryCF::applyCorrelation (mat & D) const [protected]
Apply the correlation function to a matrix of square distances.
Parameters:
D A matrix of square distances. These get overriden with the correlation for each square distance.
Definition at line 136 of file StationaryCF.cpp.
References correlation().
Referenced by covariance(), and covarianceGradient().
void StationaryCF::applyCorrelationGradient (int p, mat & D) const [protected]
Apply the gradient of the correlation function to a matrix of square distances.
Parameters:
p the number of the parameter to differentiate with respect to
D A matrix of square distances. These get overriden with the gradient of the correlation for each square distance
Definition at line 154 of file StationaryCF.cpp.
References correlationGradient().
Referenced by covarianceGradient().
Member Data Documentation
double& StationaryCF::variance [protected]
Definition at line 33 of file StationaryCF.h.
Referenced by computeDiagonalElement(), computeElement(), covariance(), covarianceGradient(), and StationaryCF().
double& StationaryCF::lengthScale [protected]
Definition at line 34 of file StationaryCF.h.
Referenced by Matern5CF::correlation(), Matern3CF::correlation(), GaussianCF::correlation(), ExponentialCF::correlation(), Matern5CF::correlationGradient(), Matern3CF::correlationGradient(), GaussianCF::correlationGradient(), ExponentialCF::correlationGradient(), and StationaryCF().
The documentation for this class was generated from the following files:
src/covariance_functions/StationaryCF.h
src/covariance_functions/StationaryCF.cpp