GPTK: GreedyMaxMinDesign Class Reference
GreedyMaxMinDesign Class Reference
#include <GreedyMaxMinDesign.h>
Public Member Functions
GreedyMaxMinDesign (double zweight=3.0)
virtual ~GreedyMaxMinDesign ()
ivec subsample (mat X, int sample_size)
Private Member Functions
vec dist (mat X, vec y)
double weightedSquareNorm (vec v)
Private Attributes
int nsamples
double zweight
Detailed Description
GREEDY MAX MIN DISTANCE RANDOM DESIGN
Subsample by adding points
Definition at line 15 of file GreedyMaxMinDesign.h.
Constructor & Destructor Documentation
GreedyMaxMinDesign::GreedyMaxMinDesign (double zweight = 3.0)
Definition at line 3 of file GreedyMaxMinDesign.cpp.
References zweight.
GreedyMaxMinDesign::~GreedyMaxMinDesign () [virtual]
Definition at line 8 of file GreedyMaxMinDesign.cpp.
Member Function Documentation
ivec GreedyMaxMinDesign::subsample (mat X, int sample_size) [virtual]
Implements Design.
Definition at line 17 of file GreedyMaxMinDesign.cpp.
References dist(), and itppext::min().
vec GreedyMaxMinDesign::dist (mat R, vec y) [private]
Returns a vector of distances between the points in R and point y
Definition at line 65 of file GreedyMaxMinDesign.cpp.
References weightedSquareNorm().
Referenced by subsample().
double GreedyMaxMinDesign::weightedSquareNorm (vec v) [private]
Computes the squared norm of vector v but last component weighted according to zweight (allows to give more importance to the z component over the x and y components)
Definition at line 83 of file GreedyMaxMinDesign.cpp.
References zweight.
Referenced by dist().
Member Data Documentation
int GreedyMaxMinDesign::nsamples [private]
Definition at line 25 of file GreedyMaxMinDesign.h.
double GreedyMaxMinDesign::zweight [private]
Definition at line 28 of file GreedyMaxMinDesign.h.
Referenced by GreedyMaxMinDesign(), and weightedSquareNorm().
The documentation for this class was generated from the following files:
src/design/GreedyMaxMinDesign.h
src/design/GreedyMaxMinDesign.cpp