GPTK: WhiteNoiseCF Class Reference
WhiteNoiseCF Class Reference
#include <WhiteNoiseCF.h>
Public Member Functions
WhiteNoiseCF (double variance)
virtual ~WhiteNoiseCF ()
double computeElement (const vec &A, const vec &B) const
double computeDiagonalElement (const vec &A) const
void covarianceGradient (mat &G, const int p, const mat &X) const
Private Attributes
double & variance
Detailed Description
Gaussian white noise (zero mean) covariance function
Definition at line 39 of file WhiteNoiseCF.h.
Constructor & Destructor Documentation
WhiteNoiseCF::WhiteNoiseCF (double _variance)
Constructor
Parameters:
_variance the noise variance
Definition at line 8 of file WhiteNoiseCF.cpp.
References CovarianceFunction::parametersNames, and variance.
WhiteNoiseCF::~WhiteNoiseCF () [virtual]
Destructor
Definition at line 18 of file WhiteNoiseCF.cpp.
Member Function Documentation
double WhiteNoiseCF::computeElement (const vec & A, const vec & B) const [inline, virtual]
Covariance between two inputs. If the two inputs are identical, this returns the noise variance, and zero otherwise.
Parameters:
A the first input
B the second input
Returns:
the noise variance if A == B, 0 otherwise
Implements CovarianceFunction.
Definition at line 30 of file WhiteNoiseCF.cpp.
References variance.
double WhiteNoiseCF::computeDiagonalElement (const vec & A) const [inline, virtual]
Variance of a single input. This always returns the noise variance.
Parameters:
A the input
Returns:
the noise variance
Reimplemented from CovarianceFunction.
Definition at line 43 of file WhiteNoiseCF.cpp.
References variance.
void WhiteNoiseCF::covarianceGradient (mat & G, const int p, const mat & X) const [virtual]
Gradient of the covariance matrix for a set of inputs, with respect to a given parameter.
Parameters:
G the gradient of cov(X,X) with respect to parameter p
p the parameter number
X a set of (row) inputs
Implements CovarianceFunction.
Definition at line 57 of file WhiteNoiseCF.cpp.
References CovarianceFunction::covariance(), CovarianceFunction::getTransform(), Transform::gradientTransform(), CovarianceFunction::parameters, and variance.
Member Data Documentation
double& WhiteNoiseCF::variance [private]
Definition at line 51 of file WhiteNoiseCF.h.
Referenced by computeDiagonalElement(), computeElement(), covarianceGradient(), and WhiteNoiseCF().
The documentation for this class was generated from the following files:
src/covariance_functions/WhiteNoiseCF.h
src/covariance_functions/WhiteNoiseCF.cpp