GPTK: MaxMinDesign Class Reference
MaxMinDesign Class Reference
#include <MaxMinDesign.h>
Public Member Functions
MaxMinDesign (int nsamples=100)
virtual ~MaxMinDesign ()
ivec subsample (mat X, int sample_size)
Private Member Functions
double distanceMin (mat X)
Private Attributes
int nsamples
Detailed Description
MAX MIN DISTANCE RANDOM DESIGN
This returns a random subsample from a set of locations in which the minimum distance between any two points is maximised. The maximisation is achieved by taking the "best" subsample (with respect to the min distance between points) out of NSAMPLE similar random subsamples.
Definition at line 15 of file MaxMinDesign.h.
Constructor & Destructor Documentation
MaxMinDesign::MaxMinDesign (int nsamples = 100)
Definition at line 3 of file MaxMinDesign.cpp.
References nsamples.
MaxMinDesign::~MaxMinDesign () [virtual]
Definition at line 14 of file MaxMinDesign.cpp.
Member Function Documentation
ivec MaxMinDesign::subsample (mat X, int n) [virtual]
Returns a random subsample of X of size n which has minimum (amongst a set of NSAMPLES similar subsamples) maximum distance between points.
Implements Design.
Definition at line 23 of file MaxMinDesign.cpp.
References distanceMin(), nsamples, and itppext::randperm().
double MaxMinDesign::distanceMin (mat X) [private]
Returns the maximum distance between any 2 points from X
Definition at line 55 of file MaxMinDesign.cpp.
Referenced by subsample().
Member Data Documentation
int MaxMinDesign::nsamples [private]
Definition at line 25 of file MaxMinDesign.h.
Referenced by MaxMinDesign(), and subsample().
The documentation for this class was generated from the following files:
src/design/MaxMinDesign.h
src/design/MaxMinDesign.cpp