GPTK: SCGModelTrainer Class Reference
SCGModelTrainer Class Reference
#include <SCGModelTrainer.h>
Public Member Functions
SCGModelTrainer (Optimisable &m)
virtual ~SCGModelTrainer ()
void Train (int numIterations)
Detailed Description
Definition at line 43 of file SCGModelTrainer.h.
Constructor & Destructor Documentation
SCGModelTrainer::SCGModelTrainer (Optimisable & m)
Definition at line 39 of file SCGModelTrainer.cpp.
References ModelTrainer::algorithmName.
SCGModelTrainer::~SCGModelTrainer () [virtual]
Definition at line 44 of file SCGModelTrainer.cpp.
Member Function Documentation
void SCGModelTrainer::Train (int numIterations) [virtual]
Implements ModelTrainer.
Definition at line 48 of file SCGModelTrainer.cpp.
References ModelTrainer::analyticGradients, ModelTrainer::checkGradient(), ModelTrainer::display, ModelTrainer::errorFunction(), ModelTrainer::errorGradients(), ModelTrainer::errorTolerance, ModelTrainer::functionValue, ModelTrainer::getParameters(), ModelTrainer::gradientCheck, itppext::min(), ModelTrainer::parameterTolerance, and ModelTrainer::setParameters().
The documentation for this class was generated from the following files:
src/optimisation/SCGModelTrainer.h
src/optimisation/SCGModelTrainer.cpp