GPTK: NeuralNetCF Class Reference
NeuralNetCF Class Reference
#include <NeuralNetCF.h>
Public Member Functions
NeuralNetCF (double lengthscale, double variance, double offset=0)
virtual ~NeuralNetCF ()
double computeElement (const vec &A, const vec &B) const
virtual void covarianceGradient (mat &grad, const int parameterNumber, const mat &X) const
Private Attributes
double & sigma2
double & offset
double & variance
Detailed Description
Neural network covariance function
This covariance function is of the form
s * asin[ r * (1+x'*y) / sqrt((1+r+r*x'*x)*(1+r+r*y'*y)) ]
where r = 1/(lengthscale^2) and s = variance is a scaling factor.
(C) 2009 Remi Barillec <r.barillec@aston.ac.uk>
Definition at line 17 of file NeuralNetCF.h.
Constructor & Destructor Documentation
NeuralNetCF::NeuralNetCF (double lengthscale, double variance, double offset = 0)
Definition at line 6 of file NeuralNetCF.cpp.
References offset, CovarianceFunction::parametersNames, sigma2, and variance.
NeuralNetCF::~NeuralNetCF () [virtual]
Destructor
Definition at line 27 of file NeuralNetCF.cpp.
Member Function Documentation
double NeuralNetCF::computeElement (const vec & A, const vec & B) const [inline, virtual]
Covariance between two points A and B
Implements CovarianceFunction.
Definition at line 34 of file NeuralNetCF.cpp.
References offset, sigma2, and variance.
void NeuralNetCF::covarianceGradient (mat & grad, const int parameterNumber, const mat & X) const [virtual]
Gradient of cov(X) w.r.t. given parameter number
Implements CovarianceFunction.
Definition at line 54 of file NeuralNetCF.cpp.
References CovarianceFunction::covariance(), CovarianceFunction::getNumberParameters(), CovarianceFunction::getParameter(), CovarianceFunction::getTransform(), Transform::gradientTransform(), offset, sigma2, and variance.
Member Data Documentation
double& NeuralNetCF::sigma2 [private]
Definition at line 28 of file NeuralNetCF.h.
Referenced by computeElement(), covarianceGradient(), and NeuralNetCF().
double& NeuralNetCF::offset [private]
Definition at line 29 of file NeuralNetCF.h.
Referenced by computeElement(), covarianceGradient(), and NeuralNetCF().
double& NeuralNetCF::variance [private]
Definition at line 30 of file NeuralNetCF.h.
Referenced by computeElement(), covarianceGradient(), and NeuralNetCF().
The documentation for this class was generated from the following files:
src/covariance_functions/NeuralNetCF.h
src/covariance_functions/NeuralNetCF.cpp