GPTK: SamplingLikelihood Class Reference
SamplingLikelihood Class Reference
#include <SamplingLikelihood.h>
Public Member Functions
SamplingLikelihood ()
SamplingLikelihood (double(*_transform)(double))
virtual ~SamplingLikelihood ()
void setSamplingParameters (int Samples, int Cycles)
virtual double updateCoefficients (double &K1, double &K2, double Observation, double ModelMean, double ModelVariance) const =0
Static Public Member Functions
static double identity (const double x)
Protected Attributes
int numberSamples
int numberCycles
double(* transform)(double)
Detailed Description
A sampling-based likelihood model. This allows for an additional transform (mapping from state space to observation space) to be specified. By default, the identity is used (the state variables are observed directly).
Definition at line 44 of file SamplingLikelihood.h.
Constructor & Destructor Documentation
SamplingLikelihood::SamplingLikelihood ()
Definition at line 3 of file SamplingLikelihood.cpp.
References identity(), numberCycles, numberSamples, and transform.
SamplingLikelihood::SamplingLikelihood (double(*)(double) _transform)
Definition at line 10 of file SamplingLikelihood.cpp.
References numberCycles, numberSamples, and transform.
SamplingLikelihood::~SamplingLikelihood () [virtual]
Definition at line 17 of file SamplingLikelihood.cpp.
Member Function Documentation
void SamplingLikelihood::setSamplingParameters (int Samples, int Cycles)
Definition at line 22 of file SamplingLikelihood.cpp.
References numberCycles, and numberSamples.
virtual double SamplingLikelihood::updateCoefficients (double & K1, double & K2, double Observation, double ModelMean, double ModelVariance) const [pure virtual]
Implements LikelihoodType.
Implemented in ExponentialSampLikelihood, and GaussianSampLikelihood.
static double SamplingLikelihood::identity (const double x) [inline, static]
Definition at line 68 of file SamplingLikelihood.h.
Referenced by SamplingLikelihood().
Member Data Documentation
int SamplingLikelihood::numberSamples [protected]
Definition at line 71 of file SamplingLikelihood.h.
Referenced by SamplingLikelihood(), setSamplingParameters(), GaussianSampLikelihood::updateCoefficients(), and ExponentialSampLikelihood::updateCoefficients().
int SamplingLikelihood::numberCycles [protected]
Definition at line 72 of file SamplingLikelihood.h.
Referenced by SamplingLikelihood(), setSamplingParameters(), GaussianSampLikelihood::updateCoefficients(), and ExponentialSampLikelihood::updateCoefficients().
double(* SamplingLikelihood::transform)(double) [protected]
Referenced by ExponentialSampLikelihood::ExponentialSampLikelihood(), GaussianSampLikelihood::GaussianSampLikelihood(), SamplingLikelihood(), GaussianSampLikelihood::updateCoefficients(), and ExponentialSampLikelihood::updateCoefficients().
The documentation for this class was generated from the following files:
src/likelihood_models/SamplingLikelihood.h
src/likelihood_models/SamplingLikelihood.cpp