GPTK: Transform Class Reference
Transform Class Reference
#include <Transform.h>
Public Member Functions
Transform ()
virtual ~Transform ()
virtual double forwardTransform (const double a) const =0
virtual double backwardTransform (const double b) const =0
virtual double gradientTransform (const double g) const =0
string type () const
Protected Attributes
string transformName
Detailed Description
Definition at line 41 of file Transform.h.
Constructor & Destructor Documentation
Transform::Transform ()
Definition at line 3 of file Transform.cpp.
Transform::~Transform () [virtual]
Definition at line 8 of file Transform.cpp.
Member Function Documentation
virtual double Transform::forwardTransform (const double a) const [pure virtual]
Implemented in IdentityTransform, and LogTransform.
virtual double Transform::backwardTransform (const double b) const [pure virtual]
Implemented in IdentityTransform, and LogTransform.
virtual double Transform::gradientTransform (const double g) const [pure virtual]
Implemented in IdentityTransform, and LogTransform.
Referenced by WhiteNoiseCF::covarianceGradient(), StationaryCF::covarianceGradient(), NeuralNetCF::covarianceGradient(), and ConstantCF::covarianceGradient().
string Transform::type () const
Definition at line 12 of file Transform.cpp.
References transformName.
Member Data Documentation
string Transform::transformName [protected]
Definition at line 54 of file Transform.h.
Referenced by IdentityTransform::IdentityTransform(), LogTransform::LogTransform(), and type().
The documentation for this class was generated from the following files:
src/parameter_transforms/Transform.h
src/parameter_transforms/Transform.cpp