GPTK: CovarianceFunction Class Reference
CovarianceFunction Class Reference
#include <CovarianceFunction.h>
Public Member Functions
CovarianceFunction (string name, int numParameters)
CovarianceFunction (string name, int numParameters, Transform *t)
virtual ~CovarianceFunction ()
virtual double computeElement (const vec &A, const vec &B) const =0
virtual double computeDiagonalElement (const vec &A) const
virtual void covariance (double &c, const vec &X) const
virtual void covariance (mat &C, const mat &X) const
virtual void covariance (vec &C, const mat &X, const vec &x) const
virtual void covariance (mat &C, const mat &X1, const mat &X2) const
virtual void covarianceGradient (mat &grad, const int parameterNumber, const mat &X) const =0
virtual void computeDiagonal (mat &C, const mat &X) const
virtual void computeDiagonal (vec &C, const mat &X) const
virtual void setParameter (const int parameterNumber, const double value)
virtual double getParameter (const int parameterNumber) const
virtual string getParameterName (const int parameterNumber) const
virtual void setTransform (int parameterNumber, Transform *newTransform)
virtual Transform * getTransform (int parameterNumber) const
virtual void setParameters (const vec p)
virtual vec getParameters ()
virtual void setTransformedParameters (const vec p)
virtual vec getTransformedParameters ()
int getNumberParameters () const
virtual void displayCovarianceParameters (int nspaces=0) const
Protected Member Functions
void setDefaultTransform (Transform *t)
void applyDefaultTransform ()
Protected Attributes
string covarianceName
int numberParameters
bool transformsApplied
double * parameters
vector< string > parametersNames
Transform * defaultTransform
vector< Transform * > transforms
Detailed Description
Abstract class for covariance function objects. This should be overloaded by specific covariance functions.
Transforms are applied to the parameters of the covariance function to ensure they remain sensible when being optimised via Maximum Likelihood. By default, the transform is set to identity, i.e. the parameters are optimised accross the whole real space. Specific covariance should overload the setDefaultTransforms() method to set sensible transforms for all parameters (e.g. one could use a LogTransform to constrain some parameters to remain positive).
Definition at line 55 of file CovarianceFunction.h.
Constructor & Destructor Documentation
CovarianceFunction::CovarianceFunction (string name, int numParameters)
Constructor
Parameters:
name a string identifier for the covariance function
numParameters the number of parameters for this covariance function
Definition at line 11 of file CovarianceFunction.cpp.
References applyDefaultTransform(), covarianceName, defaultTransform, numberParameters, parameters, and parametersNames.
CovarianceFunction::CovarianceFunction (string name, int numParameters, Transform * t)
Constructor
Parameters:
name a string identifier for the covariance function
numParameters the number of parameters for this covariance function
t the transform to be used for all parameters
Definition at line 31 of file CovarianceFunction.cpp.
References covarianceName, numberParameters, parameters, parametersNames, and setDefaultTransform().
CovarianceFunction::~CovarianceFunction () [virtual]
Default destructor
Definition at line 48 of file CovarianceFunction.cpp.
Member Function Documentation
virtual double CovarianceFunction::computeElement (const vec & A, const vec & B) const [pure virtual]
Implemented in ConstantCF, NeuralNetCF, StationaryCF, SumCF, and WhiteNoiseCF.
Referenced by computeDiagonalElement(), and covariance().
double CovarianceFunction::computeDiagonalElement (const vec & A) const [virtual]
Compute the variance of a diagonal element, i.e. cov(A,A) This is the default and returns computeElement(A,A). This should be overridden when possible with a more efficient implementation, specific to the type of covariance (for instance, for stationary covariance functions, this takes the value of the variance parameter).
Reimplemented in ConstantCF, StationaryCF, SumCF, and WhiteNoiseCF.
Definition at line 162 of file CovarianceFunction.cpp.
References computeElement().
Referenced by computeDiagonal(), and covariance().
void CovarianceFunction::covariance (double & c, const vec & x) const [virtual]
Compute the auto-covariance of a single input
Parameters:
c The auto-covariance of x
x An input vector
Definition at line 59 of file CovarianceFunction.cpp.
Referenced by PSGP::compEvidence(), PSGP::compEvidenceApproximate(), PSGP::compEvidenceUpperBound(), covariance(), WhiteNoiseCF::covarianceGradient(), NeuralNetCF::covarianceGradient(), PSGP::EP_updateIntermediateComputations(), GaussianProcess::gradient(), PSGP::gradientEvidenceApproximate(), PSGP::gradientEvidenceUpperBound(), GaussianProcess::loglikelihood(), PSGP::makePredictions(), GaussianProcess::makePredictions(), PSGP::recomputePosterior(), and PSGP::simulate().
void CovarianceFunction::covariance (mat & C, const mat & X) const [virtual]
Compute the covariance matrix of a set of inputs
Parameters:
C The covariance matrix of X
X A matrix of inputs (one input per row)
Reimplemented in StationaryCF.
Definition at line 72 of file CovarianceFunction.cpp.
References computeDiagonalElement(), and computeElement().
void CovarianceFunction::covariance (vec & c, const mat & X, const vec & x) const [virtual]
Gradient of the covariance matrix of a set of inputs with respect to the parameters of the covariance function
Parameters:
g The gradient vector
X A set of inputs (one per row) Covariance between a set of n inputs X and another input x
c The nx1 vector covariance vector cov(X,x)
X A set of n inputs (one per row)
x Another input
Definition at line 124 of file CovarianceFunction.cpp.
References covariance().
void CovarianceFunction::covariance (mat & C, const mat & X1, const mat & X2) const [virtual]
Covariance between two sets of inputs X1 and X2
Parameters:
C The nxm covariance matrix cov(X1,X2)
X1 A set of n inputs
X2 A set of m inputs
Definition at line 140 of file CovarianceFunction.cpp.
References computeElement().
virtual void CovarianceFunction::covarianceGradient (mat & grad, const int parameterNumber, const mat & X) const [pure virtual]
Implemented in ConstantCF, NeuralNetCF, StationaryCF, SumCF, and WhiteNoiseCF.
Referenced by GaussianProcess::gradient(), PSGP::gradientEvidenceApproximate(), and PSGP::gradientEvidenceUpperBound().
void CovarianceFunction::computeDiagonal (mat & C, const mat & X) const [virtual]
Diagonal covariance matrix cov(X,X). The non-diagonal terms are ignored.
Parameters:
C A diagonal matrix with with diagonal elements C_ii = cov(X_i, X_i)
X A set of inputs (one per row)
Definition at line 172 of file CovarianceFunction.cpp.
References computeDiagonalElement().
Referenced by PSGP::makePredictions(), and GaussianProcess::makePredictions().
void CovarianceFunction::computeDiagonal (vec & C, const mat & X) const [virtual]
Diagonal elements of the matrix cov(X,X).
Parameters:
C A vector of diagonal elements C_i = cov(X_i, X_i)
X A set of inputs (one per row)
Definition at line 190 of file CovarianceFunction.cpp.
References computeDiagonalElement().
void CovarianceFunction::setParameter (const int parameterNumber, const double value) [virtual]
Set the value of a given parameter
Parameters:
p the parameter number
value the new value of the parameter
Reimplemented in SumCF.
Definition at line 339 of file CovarianceFunction.cpp.
References numberParameters, and parameters.
Referenced by setParameters(), and setTransformedParameters().
double CovarianceFunction::getParameter (const int parameterNumber) const [virtual]
Return a given parameter value
Parameters:
p the parameter number
Returns:
the value of parameter number p
Reimplemented in SumCF.
Definition at line 325 of file CovarianceFunction.cpp.
References numberParameters, and parameters.
Referenced by NeuralNetCF::covarianceGradient(), ConstantCF::covarianceGradient(), displayCovarianceParameters(), getParameters(), and getTransformedParameters().
string CovarianceFunction::getParameterName (const int parameterNumber) const [virtual]
Returns the name of the given parameter
Parameters:
parameterNumber the number of the parameter
Returns:
the name of the parameter
Reimplemented in SumCF.
Definition at line 206 of file CovarianceFunction.cpp.
References parametersNames.
Referenced by displayCovarianceParameters().
void CovarianceFunction::setTransform (int parameterNumber, Transform * newTransform) [virtual]
Set the transform for a given parameter.
Parameters:
parameterNumber The parameter number
newTransform The transform to be applied to the parameter (e.g. a pointer to an instance of LogTransform)
Reimplemented in SumCF.
Definition at line 390 of file CovarianceFunction.cpp.
References numberParameters, and transforms.
Transform * CovarianceFunction::getTransform (int parameterNumber) const [virtual]
Get the transform for a given parameter of the covariance function
Parameters:
parameterNumber The parameter number
Returns:
a pointer to the transform object currently applied to that parameter
Reimplemented in SumCF.
Definition at line 406 of file CovarianceFunction.cpp.
References getNumberParameters(), and transforms.
Referenced by WhiteNoiseCF::covarianceGradient(), StationaryCF::covarianceGradient(), NeuralNetCF::covarianceGradient(), and ConstantCF::covarianceGradient().
void CovarianceFunction::setParameters (const vec p) [virtual]
Set the parameters of the covariance function to that of the argument vector.
Parameters:
p Vector of new parameter values
Definition at line 261 of file CovarianceFunction.cpp.
References numberParameters, and setParameter().
vec CovarianceFunction::getParameters () [virtual]
Get the current covariance function parameters
Returns:
A vector of parameter values
Definition at line 243 of file CovarianceFunction.cpp.
References getParameter(), and numberParameters.
void CovarianceFunction::setTransformedParameters (const vec p) [virtual]
Set the parameters of the covariance function to that of the argument vector. The argument vector must contain one value for each parameter and these values must be transformed (i.e. if a parameter is optimised in log-space, then its new value must be in log-space too).
Parameters:
p Vector of new parameter values (transformed)
Reimplemented in SumCF.
Definition at line 300 of file CovarianceFunction.cpp.
References getNumberParameters(), setParameter(), and transforms.
Referenced by PSGP::setTransformedParameters(), and GaussianProcess::setTransformedParameters().
vec CovarianceFunction::getTransformedParameters () [virtual]
Get the current covariance function parameters (transformed)
Returns:
A vector containing all parameters of the covariance function, in transformed space (e.g. log-space for positive parameters).
Reimplemented in SumCF.
Definition at line 278 of file CovarianceFunction.cpp.
References getParameter(), numberParameters, and transforms.
Referenced by PSGP::getTransformedParameters(), and GaussianProcess::getTransformedParameters().
int CovarianceFunction::getNumberParameters () const
Returns the number of parameters in the covariance function
Returns:
The number of parameters in the covariance function
Definition at line 314 of file CovarianceFunction.cpp.
References numberParameters.
Referenced by SumCF::add(), NeuralNetCF::covarianceGradient(), getTransform(), PSGP::gradient(), GaussianProcess::gradient(), PSGP::gradientEvidence(), PSGP::gradientEvidenceApproximate(), PSGP::gradientEvidenceUpperBound(), SumCF::reindex(), and setTransformedParameters().
void CovarianceFunction::displayCovarianceParameters (int nspaces = 0) const [virtual]
Display information about the current parameters of the covariance function. This can be indented by an optional number of space characters (useful for mixtures of nested covariance functions).
Parameters:
nspaces Number of space characters to indent by.
Reimplemented in SumCF.
Definition at line 219 of file CovarianceFunction.cpp.
References covarianceName, getParameter(), getParameterName(), numberParameters, and transforms.
Referenced by PSGP::compEvidenceUpperBound().
void CovarianceFunction::setDefaultTransform (Transform * t) [protected]
Set the default transform for all parameters. The new transform is applied immediately.
Parameters:
t a pointer to an instance of Transform
Definition at line 374 of file CovarianceFunction.cpp.
References applyDefaultTransform(), and defaultTransform.
Referenced by CovarianceFunction().
void CovarianceFunction::applyDefaultTransform () [protected]
Applies the default transform to all parameters. By default, the default transform is a LogTransform (meaning all parameters are assumed positive). A different default transform can be specified in the constructor or using the setDefaultTransform method. Individual transforms can also be set for each parameter using the setTransform method.
See also:
CovarianceFunction, setDefaultTransform, setTransform
Definition at line 358 of file CovarianceFunction.cpp.
References defaultTransform, numberParameters, transforms, and transformsApplied.
Referenced by CovarianceFunction(), and setDefaultTransform().
Member Data Documentation
string CovarianceFunction::covarianceName [protected]
Definition at line 97 of file CovarianceFunction.h.
Referenced by CovarianceFunction(), and displayCovarianceParameters().
int CovarianceFunction::numberParameters [protected]
Definition at line 98 of file CovarianceFunction.h.
Referenced by SumCF::add(), applyDefaultTransform(), Matern5CF::correlationGradient(), Matern3CF::correlationGradient(), GaussianCF::correlationGradient(), ExponentialCF::correlationGradient(), CovarianceFunction(), StationaryCF::covarianceGradient(), displayCovarianceParameters(), getNumberParameters(), getParameter(), getParameters(), getTransformedParameters(), setParameter(), setParameters(), and setTransform().
bool CovarianceFunction::transformsApplied [protected]
Definition at line 99 of file CovarianceFunction.h.
Referenced by applyDefaultTransform().
double* CovarianceFunction::parameters [protected]
Definition at line 101 of file CovarianceFunction.h.
Referenced by CovarianceFunction(), WhiteNoiseCF::covarianceGradient(), StationaryCF::covarianceGradient(), getParameter(), and setParameter().
vector<string> CovarianceFunction::parametersNames [protected]
Definition at line 102 of file CovarianceFunction.h.
Referenced by ConstantCF::ConstantCF(), CovarianceFunction(), getParameterName(), NeuralNetCF::NeuralNetCF(), StationaryCF::StationaryCF(), and WhiteNoiseCF::WhiteNoiseCF().
Transform* CovarianceFunction::defaultTransform [protected]
Definition at line 104 of file CovarianceFunction.h.
Referenced by applyDefaultTransform(), CovarianceFunction(), and setDefaultTransform().
vector<Transform *> CovarianceFunction::transforms [protected]
Definition at line 105 of file CovarianceFunction.h.
Referenced by applyDefaultTransform(), displayCovarianceParameters(), getTransform(), getTransformedParameters(), setTransform(), and setTransformedParameters().
The documentation for this class was generated from the following files:
src/covariance_functions/CovarianceFunction.h
src/covariance_functions/CovarianceFunction.cpp