GPTK: GraphPlotter Class Reference
GraphPlotter Class Reference
#include <GraphPlotter.h>
Public Member Functions
GraphPlotter ()
~GraphPlotter ()
void sendCommand (const char *command,...)
void setYLabel (const string label)
void setXLabel (const string label)
void plotPoints (const vec &x, const vec &y, const string title, const pointStyle ps, const plotColor pc)
void clearPlot ()
Private Attributes
FILE * plotterStream
vector< string > tempList
Detailed Description
Definition at line 44 of file GraphPlotter.h.
Constructor & Destructor Documentation
GraphPlotter::GraphPlotter ()
Definition at line 6 of file GraphPlotter.cpp.
References plotterStream.
GraphPlotter::~GraphPlotter ()
Definition at line 17 of file GraphPlotter.cpp.
References clearPlot(), and plotterStream.
Member Function Documentation
void GraphPlotter::sendCommand (const char * command, ...)
Definition at line 46 of file GraphPlotter.cpp.
References plotterStream.
Referenced by plotPoints(), setXLabel(), and setYLabel().
void GraphPlotter::setYLabel (const string label)
Definition at line 60 of file GraphPlotter.cpp.
References sendCommand().
void GraphPlotter::setXLabel (const string label)
Definition at line 67 of file GraphPlotter.cpp.
References sendCommand().
void GraphPlotter::plotPoints (const vec & x, const vec & y, const string title, const pointStyle ps, const plotColor pc)
Definition at line 74 of file GraphPlotter.cpp.
References LINE, sendCommand(), and tempList.
void GraphPlotter::clearPlot ()
Definition at line 34 of file GraphPlotter.cpp.
References tempList.
Referenced by ~GraphPlotter().
Member Data Documentation
FILE* GraphPlotter::plotterStream [private]
Definition at line 57 of file GraphPlotter.h.
Referenced by GraphPlotter(), sendCommand(), and ~GraphPlotter().
vector<string> GraphPlotter::tempList [private]
Definition at line 58 of file GraphPlotter.h.
Referenced by clearPlot(), and plotPoints().
The documentation for this class was generated from the following files:
src/plotting/GraphPlotter.h
src/plotting/GraphPlotter.cpp