GPTK: ModelTrainer Class Reference
ModelTrainer Class Reference
#include <ModelTrainer.h>
Public Member Functions
ModelTrainer (Optimisable &m)
virtual ~ModelTrainer ()
void Summary () const
virtual void Train (int numIterations)=0
void setDisplay (bool b)
void setCheckGradient (bool b)
void setAnalyticGradients (bool b)
void setErrorTolerance (double d)
void setLineMinimiserIterations (int i)
void setLineMinimiserParameterTolerance (double d)
void setFiniteDifferenceDelta (double d)
void setOptimisationMask (bvec &m)
void checkGradient ()
Protected Member Functions
vec numericalGradients (const vec params)
double calculateNumericalGradient (const int parameterNumber, const vec params)
double errorFunction (vec params)
vec errorGradients (vec params)
vec getParameters ()
void setParameters (const vec p)
double lineFunction (vec x, double lambda, vec direction)
void lineMinimiser (double &fx, double &x, double fa, vec params, vec direction)
void bracketMinimum (double &br_min, double &br_mid, double &br_max, double a, double b, double fa, vec params, vec direction)
Protected Attributes
Optimisable & model
bool display
double errorTolerance
double parameterTolerance
bool gradientCheck
bool analyticGradients
int functionEvaluations
int gradientEvaluations
double functionValue
int lineMinimiserIterations
double lineMinimiserParameterTolerance
bool maskSet
bvec optimisationMask
double epsilon
string algorithmName
Detailed Description
Definition at line 47 of file ModelTrainer.h.
Constructor & Destructor Documentation
ModelTrainer::ModelTrainer (Optimisable & m)
Definition at line 43 of file ModelTrainer.cpp.
References analyticGradients, display, epsilon, errorTolerance, functionEvaluations, functionValue, gradientCheck, gradientEvaluations, lineMinimiserIterations, lineMinimiserParameterTolerance, maskSet, and parameterTolerance.
ModelTrainer::~ModelTrainer () [virtual]
Definition at line 65 of file ModelTrainer.cpp.
Member Function Documentation
void ModelTrainer::Summary () const
Definition at line 235 of file ModelTrainer.cpp.
References algorithmName, errorTolerance, functionEvaluations, functionValue, gradientEvaluations, and parameterTolerance.
virtual void ModelTrainer::Train (int numIterations) [pure virtual]
Implemented in SCGModelTrainer.
void ModelTrainer::setDisplay (bool b) [inline]
Definition at line 56 of file ModelTrainer.h.
References display.
void ModelTrainer::setCheckGradient (bool b) [inline]
Definition at line 57 of file ModelTrainer.h.
References gradientCheck.
void ModelTrainer::setAnalyticGradients (bool b) [inline]
Definition at line 58 of file ModelTrainer.h.
References analyticGradients.
void ModelTrainer::setErrorTolerance (double d) [inline]
Definition at line 59 of file ModelTrainer.h.
References errorTolerance.
void ModelTrainer::setLineMinimiserIterations (int i) [inline]
Definition at line 61 of file ModelTrainer.h.
References lineMinimiserIterations.
void ModelTrainer::setLineMinimiserParameterTolerance (double d) [inline]
Definition at line 62 of file ModelTrainer.h.
References lineMinimiserParameterTolerance.
void ModelTrainer::setFiniteDifferenceDelta (double d) [inline]
Definition at line 64 of file ModelTrainer.h.
References epsilon.
void ModelTrainer::setOptimisationMask (bvec & m) [inline]
Definition at line 66 of file ModelTrainer.h.
References maskSet, and optimisationMask.
void ModelTrainer::checkGradient ()
Definition at line 191 of file ModelTrainer.cpp.
References calculateNumericalGradient(), getParameters(), Optimisable::gradient(), maskSet, model, and optimisationMask.
Referenced by SCGModelTrainer::Train().
vec ModelTrainer::numericalGradients (const vec params) [protected]
Definition at line 117 of file ModelTrainer.cpp.
References calculateNumericalGradient().
Referenced by errorGradients().
double ModelTrainer::calculateNumericalGradient (const int parameterNumber, const vec params) [protected]
Definition at line 130 of file ModelTrainer.cpp.
References epsilon, and errorFunction().
Referenced by checkGradient(), and numericalGradients().
double ModelTrainer::errorFunction (vec params) [protected]
Definition at line 70 of file ModelTrainer.cpp.
References functionEvaluations, getParameters(), model, Optimisable::objective(), and setParameters().
Referenced by calculateNumericalGradient(), lineFunction(), and SCGModelTrainer::Train().
vec ModelTrainer::errorGradients (vec params) [protected]
Definition at line 85 of file ModelTrainer.cpp.
References analyticGradients, getParameters(), Optimisable::gradient(), gradientEvaluations, maskSet, model, numericalGradients(), optimisationMask, and setParameters().
Referenced by SCGModelTrainer::Train().
vec ModelTrainer::getParameters () [protected]
Definition at line 164 of file ModelTrainer.cpp.
References Optimisable::getTransformedParameters(), and model.
Referenced by checkGradient(), errorFunction(), errorGradients(), lineFunction(), and SCGModelTrainer::Train().
void ModelTrainer::setParameters (const vec p) [protected]
Definition at line 147 of file ModelTrainer.cpp.
References Optimisable::getTransformedParameters(), maskSet, model, optimisationMask, and Optimisable::setTransformedParameters().
Referenced by errorFunction(), errorGradients(), lineFunction(), and SCGModelTrainer::Train().
double ModelTrainer::lineFunction (vec x, double lambda, vec direction) [protected]
Definition at line 248 of file ModelTrainer.cpp.
References errorFunction(), getParameters(), and setParameters().
Referenced by bracketMinimum(), and lineMinimiser().
void ModelTrainer::lineMinimiser (double & fx, double & x, double fa, vec params, vec direction) [protected]
Definition at line 257 of file ModelTrainer.cpp.
References bracketMinimum(), CPHI, functionValue, lineFunction(), lineMinimiserIterations, lineMinimiserParameterTolerance, TINY, and TOL.
void ModelTrainer::bracketMinimum (double & br_min, double & br_mid, double & br_max, double a, double b, double fa, vec params, vec direction) [protected]
Definition at line 391 of file ModelTrainer.cpp.
References lineFunction(), PHI, and TINY.
Referenced by lineMinimiser().
Member Data Documentation
Optimisable& ModelTrainer::model [protected]
Definition at line 85 of file ModelTrainer.h.
Referenced by checkGradient(), errorFunction(), errorGradients(), getParameters(), and setParameters().
bool ModelTrainer::display [protected]
Definition at line 87 of file ModelTrainer.h.
Referenced by ModelTrainer(), setDisplay(), and SCGModelTrainer::Train().
double ModelTrainer::errorTolerance [protected]
Definition at line 88 of file ModelTrainer.h.
Referenced by ModelTrainer(), setErrorTolerance(), Summary(), and SCGModelTrainer::Train().
double ModelTrainer::parameterTolerance [protected]
Definition at line 89 of file ModelTrainer.h.
Referenced by ModelTrainer(), Summary(), and SCGModelTrainer::Train().
bool ModelTrainer::gradientCheck [protected]
Definition at line 90 of file ModelTrainer.h.
Referenced by ModelTrainer(), setCheckGradient(), and SCGModelTrainer::Train().
bool ModelTrainer::analyticGradients [protected]
Definition at line 91 of file ModelTrainer.h.
Referenced by errorGradients(), ModelTrainer(), setAnalyticGradients(), and SCGModelTrainer::Train().
int ModelTrainer::functionEvaluations [protected]
Definition at line 93 of file ModelTrainer.h.
Referenced by errorFunction(), ModelTrainer(), and Summary().
int ModelTrainer::gradientEvaluations [protected]
Definition at line 94 of file ModelTrainer.h.
Referenced by errorGradients(), ModelTrainer(), and Summary().
double ModelTrainer::functionValue [protected]
Definition at line 95 of file ModelTrainer.h.
Referenced by lineMinimiser(), ModelTrainer(), Summary(), and SCGModelTrainer::Train().
int ModelTrainer::lineMinimiserIterations [protected]
Definition at line 97 of file ModelTrainer.h.
Referenced by lineMinimiser(), ModelTrainer(), and setLineMinimiserIterations().
double ModelTrainer::lineMinimiserParameterTolerance [protected]
Definition at line 98 of file ModelTrainer.h.
Referenced by lineMinimiser(), ModelTrainer(), and setLineMinimiserParameterTolerance().
bool ModelTrainer::maskSet [protected]
Definition at line 100 of file ModelTrainer.h.
Referenced by checkGradient(), errorGradients(), ModelTrainer(), setOptimisationMask(), and setParameters().
bvec ModelTrainer::optimisationMask [protected]
Definition at line 101 of file ModelTrainer.h.
Referenced by checkGradient(), errorGradients(), setOptimisationMask(), and setParameters().
double ModelTrainer::epsilon [protected]
Definition at line 103 of file ModelTrainer.h.
Referenced by calculateNumericalGradient(), ModelTrainer(), and setFiniteDifferenceDelta().
string ModelTrainer::algorithmName [protected]
Definition at line 105 of file ModelTrainer.h.
Referenced by SCGModelTrainer::SCGModelTrainer(), and Summary().
The documentation for this class was generated from the following files:
src/optimisation/ModelTrainer.h
src/optimisation/ModelTrainer.cpp