GPTK: src/optimisation/ModelTrainer.h File Reference
src/optimisation/ModelTrainer.h File Reference
#include <iostream>
#include <vector>
#include <string>
#include <itpp/itbase.h>
#include "Optimisable.h"
Classes
class ModelTrainer
Variables
const double PHI = ((1.0 + sqrt(5.0)) / 2.0)
const double CPHI = (1.0 - (1.0/PHI))
const double TOL = sqrt(eps)
const double TINY = (1.0e-10)
Variable Documentation
const double CPHI = (1.0 - (1.0/PHI))
Definition at line 40 of file ModelTrainer.h.
Referenced by ModelTrainer::lineMinimiser().
const double PHI = ((1.0 + sqrt(5.0)) / 2.0)
Definition at line 39 of file ModelTrainer.h.
Referenced by ModelTrainer::bracketMinimum().
const double TINY = (1.0e-10)
Definition at line 42 of file ModelTrainer.h.
Referenced by ModelTrainer::bracketMinimum(), and ModelTrainer::lineMinimiser().
const double TOL = sqrt(eps)
Definition at line 41 of file ModelTrainer.h.
Referenced by ModelTrainer::lineMinimiser().