GPTK: itppext Namespace Reference
itppext Namespace Reference
Functions
vec ltr_vec (mat M)
vec utr_vec (mat M)
mat ltr_mat (vec v)
mat utr_mat (vec v)
double cond (mat M, int p)
ivec randperm (int n)
vec min (vec u, vec v)
mat concat_cols (mat X, vec y)
mat concat_cols (mat X, mat Y)
vec mean_rows (mat X)
vec mean_cols (mat X)
mat cov (mat X, vec &xmean)
mat cov (mat X)
void normalise (mat &X, vec &Xmean, vec &Xcovdiag)
void normalise (mat &X)
void denormalise (mat &X, vec Xmean, vec Xcovdiag)
void tokenise (const string &str, vector< string > &tokens, const string &delimiters, int stopAfter)
Function Documentation
mat itppext::concat_cols (mat X, mat Y)
Concatenation Z = [X Y]
Definition at line 149 of file itppext.cpp.
mat itppext::concat_cols (mat X, vec y)
Concatenation Z = [X y]
Definition at line 135 of file itppext.cpp.
double itppext::cond (mat M, int p)
Definition at line 101 of file itppext.cpp.
mat itppext::cov (mat X)
Definition at line 203 of file itppext.cpp.
References cov().
Referenced by PSGP::simulate().
mat itppext::cov (mat X, vec & xmean)
Unbiased empirical covariance
Definition at line 188 of file itppext.cpp.
References mean_rows().
Referenced by cov(), and normalise().
void itppext::denormalise (mat & X, vec Xmean, vec Xcovdiag)
Definition at line 243 of file itppext.cpp.
mat itppext::ltr_mat (vec v)
Returns a lower triangular matrix where the elements are taken from the argument vector in row-major order.
Parameters:
v A vector of N(N+1)/2 lower triangular elements
Returns:
A NxN lower triangular matrix
See also:
ltr_vec, utr_vec, utr_mat
Definition at line 59 of file itppext.cpp.
vec itppext::ltr_vec (mat M)
Returns the lower triangular elements (including diagonal) of a matrix, in row-major order.
Parameters:
M An NxN square matrix
Returns:
The vector of N(N+1)/2 lower triangular elements of M
See also:
ltr_mat, utr_vec, utr_mat
Definition at line 13 of file itppext.cpp.
vec itppext::mean_cols (mat X)
Empirical arithmetic mean along columns
Definition at line 175 of file itppext.cpp.
vec itppext::mean_rows (mat X)
Empirical arithmetic mean along rows
Definition at line 163 of file itppext.cpp.
Referenced by cov().
vec itppext::min (vec u, vec v)
Returns the vector of minimum elements from 2 vectors, i.e. z(i) = min(u(i), v(i)).
Definition at line 120 of file itppext.cpp.
Referenced by GreedyMaxMinDesign::subsample(), and SCGModelTrainer::Train().
void itppext::normalise (mat & X)
Definition at line 236 of file itppext.cpp.
References normalise().
void itppext::normalise (mat & X, vec & Xmean, vec & Xcovdiag)
Normalises a data set comprising a set of inputs X and a set of outputs y. The X and y arguments are overridden by their normalised versions. The mean and covariance of the original dataset are also returned.
Definition at line 216 of file itppext.cpp.
References cov().
Referenced by normalise().
ivec itppext::randperm (int n)
Returns a random permutation of numbers between 0 and N-1
Definition at line 110 of file itppext.cpp.
Referenced by PSGP::computePosterior(), MinMaxDesign::subsample(), and MaxMinDesign::subsample().
void itppext::tokenise (const string & str, vector< string > & tokens, const string & delimiters, int stopAfter)
String tokeniser - split a string into a vector of substring identified by a delimiter (space by default). Optionally, stop after a certain number of tokens has been found and return the rest of the string as the last token
Adapted from: http://oopweb.com/CPP/Documents/CPPHOWTO/Volume/C++Programming-HOWTO-7.html
Definition at line 270 of file itppext.cpp.
mat itppext::utr_mat (vec v)
Returns an upper triangular matrix where the elements are taken from the argument vector in row-major order.
Parameters:
v A vector of N(N+1)/2 upper triangular elements
Returns:
A NxN upper triangular matrix
See also:
ltr_vec, utr_vec, utr_mat
Definition at line 84 of file itppext.cpp.
vec itppext::utr_vec (mat M)
Returns the upper triangular elements (including diagonal) of a matrix, in row-major order.
Parameters:
M An NxN square matrix
Returns:
The vector of N(N+1)/2 upper triangular elements of M
See also:
utr_mat, ltr_vec, ltr_mat
Definition at line 36 of file itppext.cpp.