#! /bin/bash
DAEMON_PATH=/opt/ros/fuerte/stacks/joystick_drivers/ps3joy
DAEMON=$DAEMON_PATH/ps3joy.py
DAEMON_OPTS="--inactivity-timeout=900 --redirect-output=/var/log/ps3joy.log"
NAME=ps3joy
DESC="PS3 Controller Driver"
RUN_AS=root
PID_FILE=/var/run/ps3joy.pid
############### END EDIT ME ##################
test -x $DAEMON || exit 0
set -e
case "$1" in
 start)
       echo -n "Starting $DESC: "
       start-stop-daemon -d $DAEMON_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
       echo "$NAME."
       ;;
 stop)
       echo -n "Stopping $DESC: "
       start-stop-daemon --stop --pidfile $PID_FILE
       echo "$NAME."
       ;;
 restart|force-reload)
       echo -n "Restarting $DESC: "
       start-stop-daemon --stop --pidfile $PID_FILE
       sleep 1
       start-stop-daemon -d $DAEMON_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
       echo "$NAME."
       ;;
 *)
       N=/etc/init.d/$NAME
       echo "Usage: $N {start|stop|restart|force-reload}" >&2
       exit 1
       ;;
esac
exit 0